"""Scaffolds initial test infrastructure for projects with 0 tests."""

from pathlib import Path

from timmytest.detector.models import Ecosystem, ProjectInfo


def initialize_test_scaffold(project: ProjectInfo, root_dir: Path) -> list[str]:
    """
    Creates starter test files and directories tailored to the project's ecosystem.
    Returns a list of created files.
    """
    root = root_dir.resolve()
    created_files: list[str] = []

    if project.ecosystem == Ecosystem.PYTHON:
        tests_dir = root / "tests"
        tests_dir.mkdir(exist_ok=True)

        conftest = tests_dir / "conftest.py"
        if not conftest.exists():
            conftest.write_text(
                '"""Pytest fixtures and test configuration."""\n\nimport pytest\n',
                encoding="utf-8",
            )
            created_files.append("tests/conftest.py")

        sample_test = tests_dir / "test_example.py"
        if not sample_test.exists():
            sample_test.write_text(
                '"""Starter test file generated by TimmyTest."""\n\n'
                "def test_sanity_check():\n"
                '    """Sanity test verifying test runner is working."""\n'
                "    assert True\n",
                encoding="utf-8",
            )
            created_files.append("tests/test_example.py")

    elif project.ecosystem == Ecosystem.NODE:
        tests_dir = root / "tests"
        tests_dir.mkdir(exist_ok=True)

        is_ts = any(root.glob("**/*.ts")) or (root / "tsconfig.json").exists()
        ext = "ts" if is_ts else "js"
        sample_test = tests_dir / f"example.test.{ext}"
        if not sample_test.exists():
            sample_test.write_text(
                'import { describe, it, expect } from "vitest";\n\n'
                'describe("Sanity Check", () => {\n'
                '  it("should pass sanity check", () => {\n'
                "    expect(true).toBe(true);\n"
                "  });\n"
                "});\n",
                encoding="utf-8",
            )
            created_files.append(f"tests/example.test.{ext}")

    elif project.ecosystem == Ecosystem.RUST:
        tests_dir = root / "tests"
        tests_dir.mkdir(exist_ok=True)

        sample_test = tests_dir / "integration_test.rs"
        if not sample_test.exists():
            sample_test.write_text(
                "#[test]\nfn test_sanity_check() {\n    assert_eq!(2 + 2, 4);\n}\n",
                encoding="utf-8",
            )
            created_files.append("tests/integration_test.rs")

    elif project.ecosystem == Ecosystem.GO:
        sample_test = root / "main_test.go"
        if not sample_test.exists():
            sample_test.write_text(
                'package main\n\nimport "testing"\n\nfunc TestSanity(t *testing.T) {\n\tif 1 != 1 {\n\t\tt.Errorf("Sanity check failed")\n\t}\n}\n',
                encoding="utf-8",
            )
            created_files.append("main_test.go")

    return created_files
