"""Scaffolds starter test infrastructure and tailored test suites for discovered test gaps."""

from pathlib import Path

from timmytest.detector.models import Ecosystem, ProjectInfo


def initialize_test_scaffold(project: ProjectInfo, root_dir: Path) -> list[str]:
    """
    Creates starter test files and tailored test stubs for the project's actual
    source modules and functions based on gap analysis.
    Returns a list of created files.
    """
    root = root_dir.resolve()
    created_files: list[str] = []

    # 1. Base test infrastructure setup
    if project.ecosystem == Ecosystem.PYTHON:
        tests_dir = root / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        conftest = tests_dir / "conftest.py"
        if not conftest.exists():
            conftest.write_text(
                '"""Pytest fixtures and global test configuration."""\n\nimport pytest\n',
                encoding="utf-8",
            )
            created_files.append("tests/conftest.py")

        # Generate smart test stubs for discovered gaps
        if project.test_gaps:
            for gap in project.test_gaps[:5]:  # Generate starter stubs for top 5 gaps
                target_path = root / gap.suggested_test_file
                if not target_path.exists():
                    target_path.parent.mkdir(parents=True, exist_ok=True)

                    module_stem = Path(gap.source_module).stem
                    content_lines = [
                        f'"""Unit tests for {gap.source_module} generated by TimmyTest."""\n',
                        "import pytest\n",
                    ]

                    if gap.classes_to_test:
                        for cls_name in gap.classes_to_test:
                            content_lines.append(f"\ndef test_{module_stem}_{cls_name.lower()}_initialization():")
                            content_lines.append(f'    """Test initialization for {cls_name}."""')
                            content_lines.append("    # TODO: Implement test logic")
                            content_lines.append("    assert True\n")

                    if gap.function_details:
                        for fd in gap.function_details[:6]:
                            clean_fn = fd.name.replace(".", "_")
                            content_lines.append(f"\ndef test_{clean_fn}():")
                            if fd.docstring:
                                content_lines.append(f'    """Test for {fd.name}: {fd.docstring}."""')
                            else:
                                content_lines.append(f'    """Test for {fd.name}{fd.signature or "()"}."""')
                            content_lines.append("    # TODO: Implement test logic")
                            content_lines.append("    assert True\n")
                    elif gap.functions_to_test:
                        for fn_name in gap.functions_to_test[:6]:
                            clean_fn = fn_name.replace(".", "_")
                            content_lines.append(f"\ndef test_{clean_fn}():")
                            content_lines.append(f'    """Test for {fn_name}."""')
                            content_lines.append("    # TODO: Implement test logic")
                            content_lines.append("    assert True\n")
                    else:
                        content_lines.append(f"\ndef test_{module_stem}_sanity():")
                        content_lines.append(f'    """Sanity check for {gap.source_module}."""')
                        content_lines.append("    assert True\n")

                    target_path.write_text("\n".join(content_lines), encoding="utf-8")
                    created_files.append(gap.suggested_test_file)
        else:
            sample_test = tests_dir / "test_example.py"
            if not sample_test.exists():
                sample_test.write_text(
                    '"""Starter test file generated by TimmyTest."""\n\n'
                    "def test_sanity_check():\n"
                    '    """Sanity test verifying test runner is working."""\n'
                    "    assert True\n",
                    encoding="utf-8",
                )
                created_files.append("tests/test_example.py")

    elif project.ecosystem == Ecosystem.NODE:
        tests_dir = root / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        is_ts = any(root.glob("**/*.ts")) or (root / "tsconfig.json").exists()
        ext = "ts" if is_ts else "js"
        runner_pkg = "vitest" if project.test_framework.value == "vitest" else "jest"

        if project.test_gaps:
            for gap in project.test_gaps[:5]:
                target_path = root / gap.suggested_test_file
                if not target_path.exists():
                    target_path.parent.mkdir(parents=True, exist_ok=True)
                    stem = Path(gap.source_module).stem
                    content_lines = [
                        f'import {{ describe, it, expect }} from "{runner_pkg}";\n',
                        f'describe("{stem} module tests", () => {{',
                    ]
                    funcs = gap.functions_to_test or ["sanity"]
                    for fn in funcs[:5]:
                        content_lines.append(f'  it("should test {fn}", () => {{')
                        content_lines.append("    expect(true).toBe(true);")
                        content_lines.append("  });")
                    content_lines.append("});\n")

                    target_path.write_text("\n".join(content_lines), encoding="utf-8")
                    created_files.append(gap.suggested_test_file)
        else:
            sample_test = tests_dir / f"example.test.{ext}"
            if not sample_test.exists():
                sample_test.write_text(
                    f'import {{ describe, it, expect }} from "{runner_pkg}";\n\n'
                    'describe("Sanity Check", () => {\n'
                    '  it("should pass sanity check", () => {\n'
                    "    expect(true).toBe(true);\n"
                    "  });\n"
                    "});\n",
                    encoding="utf-8",
                )
                created_files.append(f"tests/example.test.{ext}")

    elif project.ecosystem == Ecosystem.RUST:
        tests_dir = root / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        sample_test = tests_dir / "integration_test.rs"
        if not sample_test.exists():
            sample_test.write_text(
                "#[test]\nfn test_sanity_check() {\n    assert_eq!(2 + 2, 4);\n}\n",
                encoding="utf-8",
            )
            created_files.append("tests/integration_test.rs")

    elif project.ecosystem == Ecosystem.GO:
        sample_test = root / "main_test.go"
        if not sample_test.exists():
            sample_test.write_text(
                'package main\n\nimport "testing"\n\nfunc TestSanity(t *testing.T) {\n\tif 1 != 1 {\n\t\tt.Errorf("Sanity check failed")\n\t}\n}\n',
                encoding="utf-8",
            )
            created_files.append("main_test.go")

    return created_files
