name: Bug Report
description: File a bug report to help us improve TimmyTest
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug in TimmyTest!
  - type: input
    id: os
    attributes:
      label: Operating System & Version
      placeholder: e.g. Windows 11 / Ubuntu 24.04 / macOS Sonoma
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: e.g. Python 3.12.5
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Exact commands and steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
